### ISSUE TITLE
Multiple definitions exist for class Model

### ISSUE THREAD

**Issue by popfaker** [jqhph/laravel-wherehasin#3]
This is a very package!
I see that **.ide-helper.php**  in the package affects the display of **Phpstorm**. What can I do to make **Phpstorm** friendly?
![image](https://user-images.githubusercontent.com/38718383/87778824-5bbfd100-c85e-11ea-9a5d-d1496f217c6b.png)

**Comment by jqhph** [comment]
Recently，I remove these codes about model in ide-helper.php, run
```bash
composer update dcat/laravel-wherehasin
```
