### ISSUE TITLE
能不能在包里加一个 whereDoesntHaveIn 呢?

### ISSUE THREAD

**Issue by lengqy** [jqhph/laravel-wherehasin#6]
能不能在包里加一个 whereDoesntHaveIn 呢?

**Comment by jqhph** [comment]
无法支持这个功能，即使有了也无法提高性能

**Comment by biiiiiigmonster** [comment]
> 能不能在包里加一个 whereDoesntHaveIn 呢?

可以看下这个[hasin](https://learnku.com/articles/52851)

预期上`whereDoesntHaveIn` 转换之后的语法为`SELECT * FROM tableA WHERE tableA.id NOT IN ( SELECT tableB.A_id FROM tableB WHERE xxx = 'xxx' )`，理论上`not in`是可以触发索引的，一般想要`not in`触发索引就会造成`in`很难触发索引，这种用法与常规场景相左，所以包主讲的无法提高性能原因在此

不过[hasin](https://github.com/biiiiiigmonster/hasin)已经支持`whereDoesntHaveIn`实现，具体效率提升与否可以explain看看
