### ISSUE TITLE
安装完包直接调用？什么都不用配置吗？

### ISSUE THREAD

**Issue by woann** [jqhph/laravel-wherehasin#7]
装完报错:
Column not found: 1054 Unknown column 'has_in' in 'where clause' (S

**Comment by jqhph** [comment]
没安装成功，你安装的时候报错了吧

**Comment by woann** [comment]
Extracting archiveExecuting command (CWD): unzip -qq  '/Users/wuquangong/Desktop/www/bamboo/vendor/dcat/laravel-wherehasin/61a10fee7392ad7a0c2c7337365a8f77' -d '/Users/wuquangong/Desktop/www/bamboo/vendor/composer/0bb2763c'
    REASON: Required by the root package: Install command rule (install dcat/laravel-wherehasin 0.6.0)

**Comment by woann** [comment]
重新安装不报错了问题还是那样

**Comment by jqhph** [comment]
说明你环境有问题，自己百度排查一下
